### ISSUE TITLE
Roll Your Own title not working

### ISSUE THREAD

**Issue by AndrewMac** [spicywebau/tools#18]
Hi there. I really like the "roll your own" widget thingy. I've not pushed it very far yet, but the first thing I found was that the title field wasn't working. The widget that appears just keeps using "Roll Your Own" as the title. I can't see what I might be doing wrong, so I assume this might be some kind of bug perhaps?
Cheers, Andrew

**Comment by Nav33d** [comment]
@AndrewMac Is it for Craft 3? 

We usually tend to hide the title using CSS and do everything in the template. I will fix the title logic in the next release so it takes the user defined title into account 👍

**Comment by AndrewMac** [comment]
Yes, it is Craft 3, and thanks so much for looking into this :-)
